Add `log2()<-`, `log10()<-`, `ilog2()`, and `ilog10()` functions
poissonconsulting/extras pull request #52
Opened 2023-05-26 19:53 UTC by nehill197

To allow RHS and inverse evaluation of `2^x` and `10^x`.
These functions rely on the `exp2()` and `exp10()` functions.

2023-05-27 00:08 UTC, joethorley approved these changes

2023-05-30 17:33 UTC, aylapear requested changes
- Review the parameter definitions in the params file to see if they are applicable for these functions.
- Split up the tests a bit further so each block is self contained to a single idea. So for example the edge cases block where it tests NULL, NA and Inf I would split those into their own test block as they are testing separate issues.

2023-05-30 18:37 UTC, joethorley approved these changes

2023-06-02 18:44 UTC, aylapear approved these changes

2023-06-02 18:48 UTC, merged