Speed up `dev_beta_binom()` by adding a scalar version of the log-likelihood function, a vectorized optimization routine, and memoization.
poissonconsulting/extras pull request #69
Opened 2024-08-12 16:47 UTC by nehill197

- Added a scalar case to the log-likelihood function to improve speed for scalar inputs.
- Add memoization (if package is installed) and data has > 800 rows to gain speed from repeated function calls.
- Use a vectorized optimization function to improve speed of optimization required for deviance calculation.

2024-08-12 22:26 UTC, joethorley approved these changes

2024-08-13 21:22 UTC, joethorley requested changes
I would move the optimize_R code to a .R file in /scripts so that not cluttering up the /R folder

2024-08-13 21:24 UTC, joethorley requested changes

2024-08-13 21:24 UTC, joethorley commented on R/log-lik.R
> +  # https://poissonconsulting.slack.com/archives/C07FC57Q346/p1723248220478269
I would delete this link as it's public repo and only works for poisson folks. Add info to an issue in extras and link to that if critical.

2024-08-13 22:10 UTC, joethorley approved these changes
Awesome

2024-08-14 14:29 UTC, nehill197 commented
Going to wait to merge until current CRAN submission is complete.

2025-01-07 03:37 UTC, joethorley approved these changes

2025-01-07 16:09 UTC, merged